### ISSUE TITLE
Handle more than 1 USB Button Properly

### ISSUE THREAD

**Issue by nomad-geek** [VirginiaFIRST/FTC-Match-Timer#47]
Right now, the system assumes you only have 1 button.
If you have more that 1, it doesn't work.

**Comment by nomad-geek** [comment]
I might do this one day, but it's low priority and unlikely two buttons will ever be plugged in. If they do, the first one will win.

**Comment by toebes** [comment]
With two buttons plugged in, it allows you to have one sitting right next to the field and then one at the scoring table (or even three buttons with a master controller and one at each field).  Only one button is active at a time.  The non active buttons should flash yellow or red (yellow is probably less annoying) and to take control you need to double tap the button (to avoid a heavy book or robot accidentally laying on the button) and then the other buttons become inactive.
