### ISSUE TITLE
Select Application Mode highlight lags behind when using radio buttons

### ISSUE THREAD

**Issue by Shoob189** [VirginiaFIRST/FTC-Match-Timer#52]
Clicking on image moves yellow highlight and radio button selection as expected, clicking on the radio button does NOT move yellow highlight, until next radio button click, then the yellow highlight moves to the selection (is one click behind).

Reproduce by just using the radio buttons to select the application mode.

**Comment by nomad-geek** [comment]
Oops. While I create the radio buttons, I always intended to use the pictures to select with - so I guess I never actually clicked on the radio buttons in testing. Thanks.
