### ISSUE TITLE
Configuration review (Current Settings) screen Application mode doesn't match selections

### ISSUE THREAD

**Issue by Shoob189** [VirginiaFIRST/FTC-Match-Timer#54]
On the review of your selected settings in the Initial Setup Wizard, the Application Mode name listed does not match the mode selected earlier. It is the right mode, it just isn't named the same: I selected remote only and it listed the Application Mode as server (correct, but may confuse users since they don't match).

Maybe add "Server"/"ServerClient"/"Client" to the Select Application Mode screen, or rename the Current Settings screen to use the titles from the Select Application Mode Screen.

**Comment by nomad-geek** [comment]
Good point.
