### ISSUE TITLE
Allow for branding to be controlled from the server

### ISSUE THREAD

**Issue by toebes** [VirginiaFIRST/FTC-Match-Timer#75]
When you have two or more clients, it would be nice if you could control the branding from the server instead of having to go to each client.

**Comment by nomad-geek** [comment]
Thought of this - I was trying to not push the image over the network, however, I could do this by default and allow overriding at each client.

**Comment by nomad-geek** [comment]
The more I think about it, the more I don't want to do this. I want to keep the network transfer to the minimum and moving the image one time over the network and making sure it is always right is outside of the scope of what I want to do. The image can be selected on each timer.
